<?xml version="1.0" encoding="utf-8"?><Database Name="MagoraDatabase" EntityNamespace="MagoraTest.Entity" ContextNamespace="MagoraTest.Entity" Class="MagoraDataContext" Modifier="Sealed" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\Projects;Initial Catalog=MagoraDatabase;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MagoraTest.Interfaces.Properties.Settings" SettingsPropertyName="MagoraDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MagoraData" Member="MagoraDatas">
    <Type Name="MagoraData">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="varchar(max) COLLATE SQL_Latin1_General_CP1251_CI_AS NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>